# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class PeachyServerStub(object):
    """Server implementation that starts the model and listens for requests 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
                '/PeachyServer/Submit',
                request_serializer=server__pb2.DiffRequest.SerializeToString,
                response_deserializer=server__pb2.DiffResult.FromString,
                )
        self.Shutdown = channel.unary_unary(
                '/PeachyServer/Shutdown',
                request_serializer=server__pb2.Empty.SerializeToString,
                response_deserializer=server__pb2.Empty.FromString,
                )


class PeachyServerServicer(object):
    """Server implementation that starts the model and listens for requests 
    """

    def Submit(self, request, context):
        """Submit a request (prompt) to the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeachyServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=server__pb2.DiffRequest.FromString,
                    response_serializer=server__pb2.DiffResult.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=server__pb2.Empty.FromString,
                    response_serializer=server__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PeachyServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PeachyServer(object):
    """Server implementation that starts the model and listens for requests 
    """

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PeachyServer/Submit',
            server__pb2.DiffRequest.SerializeToString,
            server__pb2.DiffResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PeachyServer/Shutdown',
            server__pb2.Empty.SerializeToString,
            server__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
